services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-runtime
    working_dir: /app/backend
    # volumes:
    #   - ./backend:/app/backend  # Remove for production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/myappdb
    depends_on:
      - mongo
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
